### PR TITLE
Add dholms as CLA signatory

### PR DESCRIPTION
**Pull request by dholms**
https://github.com/ucan-wg/spec/issues/48

### CODE REVIEW

**Review by expede — APPROVED** [review]
Thanks @dholms 🎉

**Comment by expede** [comment]
@dholms just needs a rebase. Unfortunately it needs to be submitted with your GH account. I broke the .clabot up into multiple lines to hopefully avoid this in the future

**Comment by expede** [comment]
@dholms just needs a rebase. Unfortunately it needs to be submitted with your GH account. I broke the .clabot up into multiple lines to hopefully avoid this in the future

**Comment by dholms** [comment]
Rebased 👍

**Pull request merged**
