### PR TITLE
Add gozala as CLA signatory

### PR DESCRIPTION
**Pull request by Gozala**

### CODE REVIEW

**Review by matheus23 — APPROVED** [review]

**Comment by matheus23** [comment]
Thanks @Gozala :pray: 

We need these commits to be signed though, and it looks like that's not the case. Can you [configure commit signing](https://docs.github.com/en/github-ae@latest/authentication/managing-commit-signature-verification/signing-commits) and force-push again?

**Comment by Gozala** [comment]
> Thanks @Gozala 🙏
> 
> We need these commits to be signed though, and it looks like that's not the case. Can you [configure commit signing](https://docs.github.com/en/github-ae@latest/authentication/managing-commit-signature-verification/signing-commits) and force-push again?

Ah I just edited them from the github UI, which is probably whey they didn't got signed. Will do one from my device

**Comment by Gozala** [comment]
@matheus23 Just force pushed signed commit

**Review by matheus23 — APPROVED** [review]
Great, thanks!

**Pull request merged**
